name: salestable
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.13.21

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1
  dropdown_button2: 2.3.9
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_path: ^0.7.1
  page_transition: 2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.2
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.2
  smooth_page_indicator: 1.1.0
  sqflite: ^2.3.2
  http: ^1.2.1
  timeago: ^3.6.1
  url_launcher: ^6.1.14
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.2
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.15.0
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.10.2
  youtube_player_iframe: ^5.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  top_snackbar_flutter: ^3.1.0
  equatable: ^2.0.5
  mime_type: ^1.0.0
  webviewx_plus: ^0.5.0
  numeral: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  liquid_pull_to_refresh: ^3.0.1
  skeletonizer: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  loading_indicator: ^3.1.1
  lottie: ^3.0.0
  file_picker: ^8.0.0+1
  collection: ^1.18.0
  badges: ^3.1.2
  flutter_widget_from_html_core: ^0.14.11
  get: ^4.6.6
  super_tooltip: ^2.0.7
  folder_file_saver: ^2.0.5
  permission_handler: ^11.3.0
  dio: ^5.4.0
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^25.1.35
  d_chart: ^2.6.7
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  rich_editor: ^0.0.8
  fwfh_cached_network_image: ^0.14.2
  pie_chart: ^5.4.0
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/Notification_bell.json
    - assets/lottie_animations/Salestable_Loading.json
    - assets/lottie_animations/No_Data.json
    - assets/rive_animations/
    - assets/pdfs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
